apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
  type: ClusterIP