# mysql/helm/templates/db-external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: my-db-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: my-db-secret
        property: mysql-root-password
    - secretKey: mysql-password
      remoteRef:
        key: my-db-secret
        property: mysql-password
    - secretKey: mysql-database
      remoteRef:
        key: my-db-secret
        property: mysql-database
    - secretKey: mysql-user
      remoteRef:
        key: my-db-secret
        property: mysql-user