apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade
spec:
  replicas: {{ .Values.trade.replicas }}
  selector:
    matchLabels:
      app: trade
  template:
    metadata:
      labels:
        app: trade
    spec:
      containers:
        - name: trade
          image: "{{ .Values.trade.image }}:{{ .Values.trade.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.trade.service.targetPort }}

          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: mysql-database
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: mysql-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: mysql-user

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.trade.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.trade.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 5

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: trade
