apiVersion: v1
kind: Service
metadata:
  name: trade-service
spec:
  selector:
    app: trade
  ports:
    - protocol: TCP
      port: {{ .Values.trade.service.port }}
      targetPort: {{ .Values.trade.service.targetPort }}
  type: ClusterIP