name: CD Pipeline for Frontend Service

on:
  repository_dispatch:
    types: [frontend_service_pipeline_complete]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (Always use main)
        uses: actions/checkout@v4
        with:
          ref: "main"  # ✅ Always pull the latest main branch

      # - name: Create ArgoCD app 
      #   run: |
      #     argocd app create frontend-service \
      #       --repo https://github.com/omerrevach/stockpnl_manifests.git \
      #       --path frontend/helm \
      #       --revision main \
      #       --dest-server  https://kubernetes.default.svc \
      #       --dest-namespace frontend \
      #       --directory-recurse \
      #       --sync-policy automated \
      #       --self-heal \
      #       --sync-option Prune=true \
      #       --sync-option CreateNamespace=true


      - name: GitOps update Docker image tag
        uses: adwert-it/gitops-image-update@v1
        with:
          REPOSITORY_NAME: omerrevach/stockpnl_manifests_test
          ACCESS_TOKEN: ${{ secrets.PAT }}
          BRANCH: "main"
          VALUES_FILE_PATH: "frontend/helm/values.yaml"
          VALUE_NAME: "frontend.tag"
          TAG: "${{ github.event.client_payload.build_number }}"  # ✅ Use the build number from CI pipeline

      - name: Notify on Success
        run: echo "CD pipeline completed successfully! 🚀"
