name: CD Pipeline for Frontend Service

on:
  repository_dispatch:
    types: [frontend_service_pipeline_complete]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "main" 

      - name: Update Image Tag in values.yaml
        run: |
          sed -i 's/tag:.*/tag: "frontend-${{ github.event.client_payload.build_number }}"/' frontend/helm/values.yaml
          cat frontend/helm/values.yaml  # Debugging step to verify update

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use PAT for authentication
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add frontend/helm/values.yaml
          git commit -m "Updating frontend.tag to build number ${{ github.event.client_payload.build_number }}" || echo "No changes to commit"
          git pull origin main --rebase  # Prevent conflicts before pushing
          git push https://x-access-token:${{ secrets.PAT }}@github.com/omerrevach/stockpnl_manifests_test.git main



      - name: Notify on Success
        run: echo "CD pipeline completed successfully"
